# -*- coding: utf-8 -*-
"""car_health_predection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCmAocnEotSCKqjYcfRK9flNcYjvR_l7
"""

# ============================================================
# CAR CONDITION MODEL - THESIS TRAINING PIPELINE
# ============================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import warnings

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils import shuffle

warnings.filterwarnings('ignore')

# Set professional plotting style
sns.set_theme(style="whitegrid")
PALETTE = ["#2ecc71", "#3498db", "#e74c3c"] # Green (Normal), Blue (Warning), Red (Fault)

# ============================================================
# STEP 1: DATA INTEGRATION & CLEANING
# ============================================================
print("--- Initializing Data Pipeline ---")

# Loading the two specific datasets
df1 = pd.read_csv('final_car_dataset (2).csv')
df2 = pd.read_csv('car_dataset_cleaned_enhanced.csv')

# Merge and remove redundancy
df = pd.concat([df1, df2], ignore_index=True)
df = df.drop_duplicates()
df = df.dropna()

# Physics-based filtering to ensure high-quality training data
df = df[
    (df['temperature'] >= -10) & (df['temperature'] <= 115) &
    (df['vibration_g'] >= 0) & (df['vibration_g'] <= 4) &
    (df['voltage_real'] >= 8) & (df['voltage_real'] <= 16)
]

df = shuffle(df, random_state=42)
print(f"Final Dataset Size: {len(df)} samples")

# Define Features (Excluding engine_state as requested)
feature_cols = ['temperature', 'temp_rate', 'vibration_g', 'voltage_real']
X = df[feature_cols]
y = df['label_numeric']

# ============================================================
# STEP 2: MODEL TRAINING (ANTI-OVERFITTING)
# ============================================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, stratify=y, random_state=42
)

# Regularized Random Forest to ensure generalization
model = RandomForestClassifier(
    n_estimators=150,
    max_depth=7,            # Prevents memorizing noise
    min_samples_leaf=12,    # Ensures rules are based on significant patterns
    max_features='sqrt',
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

# ============================================================
# STEP 3: VISUALIZATIONS
# ============================================================
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
plt.subplots_adjust(hspace=0.4)

# GRAPH 1: Class Distribution
sns.countplot(x=y, ax=axes[0, 0], palette=PALETTE)
axes[0, 0].set_title("1. Diagnostic Class Distribution", fontsize=14, fontweight='bold')
axes[0, 0].set_xticklabels(['Normal (0)', 'Warning (1)', 'Fault (2)'])
axes[0, 0].set_ylabel("Number of Samples")

# GRAPH 2: Feature Importance
importances = pd.Series(model.feature_importances_, index=feature_cols).sort_values()
importances.plot(kind='barh', ax=axes[0, 1], color='#34495e')
axes[0, 1].set_title("2. Sensor Impact Factor (Feature Importance)", fontsize=14, fontweight='bold')
axes[0, 1].set_xlabel("Relative Importance")

# GRAPH 3: Correlation Heatmap
corr = df[feature_cols + ['label_numeric']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", ax=axes[1, 0], cbar=False)
axes[1, 0].set_title("3. Multi-Sensor Correlation Map", fontsize=14, fontweight='bold')

# GRAPH 4: Temperature vs Voltage (Operational Clusters)
sns.scatterplot(data=df, x='temperature', y='voltage_real', hue='label_numeric',
                palette=PALETTE, alpha=0.6, ax=axes[1, 1])
axes[1, 1].set_title("4. Voltage vs Temperature Decision Clusters", fontsize=14, fontweight='bold')
axes[1, 1].legend(title='Condition', labels=['Normal', 'Warning', 'Fault'])

plt.show()

# ============================================================
# STEP 4: EVALUATION & EXPORT
# ============================================================
y_pred = model.predict(X_test)
print("\n" + "="*30)
print("FINAL PERFORMANCE REPORT")
print("="*30)
print(classification_report(y_test, y_pred, target_names=['Normal', 'Warning', 'Fault']))

# Save for Flask
joblib.dump(model, 'car_condition_model.joblib')
joblib.dump(feature_cols, 'feature_columns.joblib')
print("\nModel files exported successfully.")

import pandas as pd

# 1. Load the original datasets
# Replace these filenames with your actual file names
df_healthy = pd.read_csv('final_car_dataset (2).csv')
df_faults = pd.read_csv('car_dataset_cleaned_enhanced.csv')

print(f"Original Healthy Rows: {len(df_healthy)}")
print(f"Original Fault Rows: {len(df_faults)}")

# 2. Eliminate Redundancy (Deduplication)
# This removes rows that are exactly the same (common in IoT sensors that send the same value twice)
df_healthy = df_healthy.drop_duplicates()
df_faults = df_faults.drop_duplicates()

# 3. Handle Column Alignment
# Ensure both dataframes have the same columns before merging
# If one has 'Label' and the other doesn't, we add them here
if 'status' not in df_healthy.columns:
    df_healthy['status'] = 0  # 0 for Healthy
if 'status' not in df_faults.columns:
    df_faults['status'] = 1  # 1 for Warning/Fault

# 4. Merge the two datasets
# We use 'concat' to stack them on top of each other
combined_df = pd.concat([df_healthy, df_faults], axis=0, ignore_index=True)

# 5. Data Cleaning: Handling Missing Values
# If a sensor dropped a reading, we fill it with the average (Mean) of that column
combined_df = combined_df.fillna(combined_df.mean())

# 6. Shuffle the Data
# Crucial for Machine Learning so the model doesn't see all 'Healthy' then all 'Faults'
combined_df = combined_df.sample(frac=1, random_state=42).reset_index(drop=True)

# 7. Extract to a New CSV
output_filename = 'final_processed_maintenance_data.csv'
combined_df.to_csv(output_filename, index=False)

print("-" * 30)
print(f"Success! Final dataset saved as: {output_filename}")
print(f"Total clean rows: {len(combined_df)}")

import pandas as pd
from sklearn.utils import shuffle

# ============================================================
# STEP 1: DATA INTEGRATION & CLEANING
# ============================================================
print("--- Initializing Data Pipeline ---")

# Loading the two specific datasets
df1 = pd.read_csv('final_car_dataset (2).csv')
df2 = pd.read_csv('car_dataset_cleaned_enhanced.csv')

# Merge and remove redundancy
df = pd.concat([df1, df2], ignore_index=True)
df = df.drop_duplicates()
df = df.dropna()

# Physics-based filtering to ensure high-quality training data
df = df[
    (df['temperature'] >= -10) & (df['temperature'] <= 115) &
    (df['vibration_g'] >= 0) & (df['vibration_g'] <= 4) &
    (df['voltage_real'] >= 8) & (df['voltage_real'] <= 16)
]

# Shuffle the combined data
df = shuffle(df, random_state=42)

# --- NEW EXTRACTION CODE ---
# Save the final, processed dataset used for the model creation
df.to_csv('final_model_creation_dataset.csv', index=False)
print(f"Extraction Successful: Saved {len(df)} samples to 'final_model_creation_dataset.csv'")
# ---------------------------

print(f"Final Dataset Size: {len(df)} samples")

# Define Features (Excluding engine_state as requested)
feature_cols = ['temperature', 'temp_rate', 'vibration_g', 'voltage_real']
X = df[feature_cols]
y = df['label_numeric']

# ============================================================
# CAR CONDITION MODEL - THESIS TRAINING PIPELINE (INDIVIDUAL PLOTS)
# ============================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import warnings

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.utils import shuffle

warnings.filterwarnings('ignore')

# Set professional plotting style
sns.set_theme(style="whitegrid")
PALETTE = ["#2ecc71", "#3498db", "#e74c3c"] # Green (Normal), Blue (Warning), Red (Fault)

# ============================================================
# STEP 1: DATA INTEGRATION, CLEANING & EXTRACTION
# ============================================================
print("--- Initializing Data Pipeline ---")

df1 = pd.read_csv('final_car_dataset (2).csv')
df2 = pd.read_csv('car_dataset_cleaned_enhanced.csv')

df = pd.concat([df1, df2], ignore_index=True)
df = df.drop_duplicates()
df = df.dropna()

# Physics-based filtering
df = df[
    (df['temperature'] >= -10) & (df['temperature'] <= 115) &
    (df['vibration_g'] >= 0) & (df['vibration_g'] <= 4) &
    (df['voltage_real'] >= 8) & (df['voltage_real'] <= 16)
]

df = shuffle(df, random_state=42)

# --- MASTER DATASET EXTRACTION ---
# This is your final dataset for the thesis
df.to_csv('final_model_creation_dataset.csv', index=False)
print(f"Master dataset saved: {len(df)} samples")

# Define Features
feature_cols = ['temperature', 'temp_rate', 'vibration_g', 'voltage_real']
X = df[feature_cols]
y = df['label_numeric']

# ============================================================
# STEP 2: MODEL TRAINING
# ============================================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, stratify=y, random_state=42
)

model = RandomForestClassifier(
    n_estimators=150,
    max_depth=7,
    min_samples_leaf=12,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

# ============================================================
# STEP 3: INDIVIDUAL VISUALIZATIONS
# ============================================================
print("--- Generating Individual Plots ---")

# IMAGE 1: Class Distribution
plt.figure(figsize=(10, 6))
sns.countplot(x=y, palette=PALETTE)
plt.title("Diagnostic Class Distribution", fontsize=14, fontweight='bold')
plt.xticks([0, 1, 2], ['Normal (0)', 'Warning (1)', 'Fault (2)'])
plt.ylabel("Number of Samples")
plt.savefig('plot_1_distribution.png', dpi=300, bbox_inches='tight')
plt.close()

# IMAGE 2: Feature Importance
plt.figure(figsize=(10, 6))
importances = pd.Series(model.feature_importances_, index=feature_cols).sort_values()
importances.plot(kind='barh', color='#34495e')
plt.title("Sensor Impact Factor (Feature Importance)", fontsize=14, fontweight='bold')
plt.xlabel("Relative Importance")
plt.savefig('plot_2_importance.png', dpi=300, bbox_inches='tight')
plt.close()

# IMAGE 3: Correlation Heatmap
plt.figure(figsize=(10, 8))
corr = df[feature_cols + ['label_numeric']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", cbar=True)
plt.title("Multi-Sensor Correlation Map", fontsize=14, fontweight='bold')
plt.savefig('plot_3_correlation.png', dpi=300, bbox_inches='tight')
plt.close()

# IMAGE 4: Operational Clusters
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='temperature', y='voltage_real', hue='label_numeric', palette=PALETTE, alpha=0.6)
plt.title("Voltage vs Temperature Decision Clusters", fontsize=14, fontweight='bold')
plt.legend(title='Condition', labels=['Normal', 'Warning', 'Fault'])
plt.savefig('plot_4_clusters.png', dpi=300, bbox_inches='tight')
plt.close()

print("All 4 images have been saved to your folder.")

# ============================================================
# STEP 4: EVALUATION & EXPORT
# ============================================================
y_pred = model.predict(X_test)
print("\n" + "="*30)
print("FINAL PERFORMANCE REPORT")
print("="*30)
print(classification_report(y_test, y_pred, target_names=['Normal', 'Warning', 'Fault']))

joblib.dump(model, 'car_condition_model.joblib')
joblib.dump(feature_cols, 'feature_columns.joblib')